export const GET_ALL_CONTACTS_SUCCESS = "GET_ALL_CONTACTS_SUCCESS";
export const GET_CONTACT = "GET_CONTACT";
export const GET_ALL_CONTACTS_fAIL = "GET_ALL_CONTACTS_FAIL";
export const GET_ALL_CONTACTS_LOAD = "GET_ALL_CONTACTS_LOAD";
